-- Supabase history table contract used by collaboration-service session-end upserts.
-- The POST request in src/services/attemptHistory.ts depends on the unique
-- (session_id, user_id) constraint together with:
--   ?on_conflict=session_id,user_id
--   Prefer: resolution=merge-duplicates

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on update cascade on delete restrict,
  question_id bigint not null references questions(id) on update cascade on delete restrict,
  session_id text not null,
  partner_id uuid not null references profiles(id) on update cascade on delete restrict,
  solution text not null default '',
  created_at timestamptz not null default now()
);

create unique index if not exists history_session_user_unique
  on public.history (session_id, user_id);
